import { ECommerceHeader } from "@/components/common/header"
import { CategoryPageTemplate } from "@/features/products/components/category-page-template"

const categories = [
	{ name: "Smartphones", icon: "📱", href: "/electronics" },
	{ name: "Laptops", icon: "💻", href: "/electronics" },
	{ name: "Audio", icon: "🎧", href: "/electronics" },
	{ name: "Gaming", icon: "🎮", href: "/electronics" },
	{ name: "Cámaras", icon: "📷", href: "/electronics" },
	{ name: "Otros", icon: "⚡", href: "/electronics" },
]

const products = [
	{
		id: 1,
		name: "iPhone 15 Pro Max",
		price: "$1,299",
		originalPrice: "$1,499",
		image: "/iphone-15-pro-max.png",
		category: "Smartphones",
		brand: "Apple",
		color: "black",
		size: "Grande",
		priceValue: 1299,
	},
	{
		id: 2,
		name: "Samsung Galaxy S24",
		price: "$899",
		originalPrice: "$1,099",
		image: "/samsung-galaxy-s24.png",
		category: "Smartphones",
		brand: "Samsung",
		color: "blue",
		size: "Mediano",
		priceValue: 899,
	},
	{
		id: 3,
		name: 'MacBook Pro 16"',
		price: "$2,399",
		originalPrice: "$2,699",
		image: "/macbook-pro-16-inch.png",
		category: "Laptops",
		brand: "Apple",
		color: "black",
		size: "Grande",
		priceValue: 2399,
	},
	{
		id: 4,
		name: "Sony WH-1000XM5",
		price: "$349",
		originalPrice: "$399",
		image: "/sony-wh-1000xm5.png",
		category: "Audio",
		brand: "Sony",
		color: "black",
		size: "Mediano",
		priceValue: 349,
	},
	{
		id: 5,
		name: "PlayStation 5",
		price: "$499",
		originalPrice: "$599",
		image: "/playstation-5-console.png",
		category: "Gaming",
		brand: "Sony",
		color: "white",
		size: "Grande",
		priceValue: 499,
	},
	{
		id: 6,
		name: "Canon EOS R6",
		price: "$2,199",
		originalPrice: "$2,499",
		image: "/canon-eos-r6.png",
		category: "Cámaras",
		brand: "Canon",
		color: "black",
		size: "Mediano",
		priceValue: 2199,
	},
	{
		id: 7,
		name: "iPad Air 5th Gen",
		price: "$599",
		originalPrice: "$699",
		image: "/ipad-air-5th-gen.png",
		category: "Otros",
		brand: "Apple",
		color: "white",
		size: "Mediano",
		priceValue: 599,
	},
	{
		id: 8,
		name: "Dell XPS 13",
		price: "$1,199",
		originalPrice: "$1,399",
		image: "/dell-xps-13.png",
		category: "Laptops",
		brand: "Dell",
		color: "black",
		size: "Mediano",
		priceValue: 1199,
	},
	{
		id: 9,
		name: "AirPods Pro 2",
		price: "$249",
		originalPrice: "$299",
		image: "/airpods-pro-2nd-gen.png",
		category: "Audio",
		brand: "Apple",
		color: "white",
		size: "Pequeño",
		priceValue: 249,
	},
	{
		id: 10,
		name: "Nintendo Switch OLED",
		price: "$349",
		originalPrice: "$399",
		image: "/nintendo-switch-oled.png",
		category: "Gaming",
		brand: "Nintendo",
		color: "red",
		size: "Mediano",
		priceValue: 349,
	},
	{
		id: 11,
		name: 'LG OLED C3 55"',
		price: "$1,499",
		originalPrice: "$1,799",
		image: "/lg-oled-c3-55-inch-tv.png",
		category: "Otros",
		brand: "LG",
		color: "black",
		size: "Extra Grande",
		priceValue: 1499,
	},
	{
		id: 12,
		name: "Google Pixel 8 Pro",
		price: "$999",
		originalPrice: "$1,199",
		image: "/google-pixel-8-pro.png",
		category: "Smartphones",
		brand: "Google",
		color: "green",
		size: "Grande",
		priceValue: 999,
	},
	{
		id: 13,
		name: "Surface Laptop 5",
		price: "$1,099",
		originalPrice: "$1,299",
		image: "/placeholder.svg",
		category: "Laptops",
		brand: "Microsoft",
		color: "blue",
		size: "Mediano",
		priceValue: 1099,
	},
	{
		id: 14,
		name: "JBL Charge 5",
		price: "$179",
		originalPrice: "$199",
		image: "/placeholder.svg",
		category: "Audio",
		brand: "JBL",
		color: "black",
		size: "Mediano",
		priceValue: 179,
	},
	{
		id: 15,
		name: "Xbox Series X",
		price: "$499",
		originalPrice: "$599",
		image: "/placeholder.svg",
		category: "Gaming",
		brand: "Microsoft",
		color: "black",
		size: "Grande",
		priceValue: 499,
	},
	{
		id: 16,
		name: "GoPro Hero 12",
		price: "$399",
		originalPrice: "$499",
		image: "/placeholder.svg",
		category: "Cámaras",
		brand: "GoPro",
		color: "black",
		size: "Pequeño",
		priceValue: 399,
	},
	{
		id: 17,
		name: "Samsung Galaxy Tab S9",
		price: "$799",
		originalPrice: "$899",
		image: "/placeholder.svg",
		category: "Otros",
		brand: "Samsung",
		color: "white",
		size: "Mediano",
		priceValue: 799,
	},
	{
		id: 18,
		name: "OnePlus 12",
		price: "$699",
		originalPrice: "$799",
		image: "/placeholder.svg",
		category: "Smartphones",
		brand: "OnePlus",
		color: "green",
		size: "Mediano",
		priceValue: 699,
	},
	{
		id: 19,
		name: "Bose QuietComfort 45",
		price: "$329",
		originalPrice: "$379",
		image: "/placeholder.svg",
		category: "Audio",
		brand: "Bose",
		color: "white",
		size: "Mediano",
		priceValue: 329,
	},
	{
		id: 20,
		name: "Steam Deck 512GB",
		price: "$649",
		originalPrice: "$749",
		image: "/placeholder.svg",
		category: "Gaming",
		brand: "Valve",
		color: "black",
		size: "Mediano",
		priceValue: 649,
	},
]

const brands = ["Apple", "Samsung", "Sony", "LG", "Xiaomi", "Huawei", "Canon", "Dell", "Nintendo", "Google", "Microsoft", "JBL", "GoPro", "OnePlus", "Bose", "Valve"]
const colors = [
	{ name: "Negro", value: "black", color: "bg-black" },
	{ name: "Azul", value: "blue", color: "bg-blue-600" },
	{ name: "Rojo", value: "red", color: "bg-red-600" },
	{ name: "Verde", value: "green", color: "bg-green-600" },
	{ name: "Blanco", value: "white", color: "bg-white border-2 border-gray-300" },
]

const sizes = ["Pequeño", "Mediano", "Grande", "Extra Grande"]

export default function ElectronicsPage() {
	return (
		<div>
			<ECommerceHeader />
			<CategoryPageTemplate
				title="Electrónica"
				breadcrumb="Electrónica"
				heroTitle="Descubre nuestra variedad de productos de electrónica"
				heroSubtitle="Encuentra la tecnología más avanzada al mejor precio"
				categories={categories}
				products={products}
				brands={brands}
				colors={colors}
				sizes={sizes}
				showSizes={true}
			/>
		</div>
	)
}
